linters:
  enable-all: true
  disable:
    # These linters are deprecated
    - interfacer
    - maligned
    - scopelint
    # We use debug statements
    - forbidigo
    # We use revive instead of golint
    - golint
    # We manage long lines manually
    - lll
    # nlreturn requires about excessive newlines around return statements
    - nlreturn
    # revive isn't very configurable yet
    - revive
    # wsl requires excessive newlines around if statements
    - wsl

linters-settings:
  govet:
    # Checking for shadowed variables is experimental and disabled by default
    check-shadowing: true

  whitespace:
    # Enforce newlines (or comments) after every multi-line if statement
    multi-if: true
