name: CI

on: [push, pull_request]

jobs:
  build_and_lint:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Compile the project (without actually generating a final binary)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target x86_64-pc-windows-msvc

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Install clippy
        run: rustup component add clippy

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  discord:
    name: Discord Failure Notification
    needs: [build_and_lint]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: ""
